project_id = "kqqavolxhrhfcwruzcyh"

[functions.send-invite]
verify_jwt = false

[functions.import-financial-data]
verify_jwt = false

[functions.import-customers-contracts]
verify_jwt = false

[functions.intercom-webhook]
verify_jwt = false

[functions.sync-intercom-tickets]
verify_jwt = false

[functions.get-intercom-conversation]
verify_jwt = false

[functions.resend-inbound]
verify_jwt = false

[functions.enrich-customer-domains]
verify_jwt = false

[functions.download-attachment]
verify_jwt = false

[functions.slack-webhook]
verify_jwt = false

[functions.api-customers]
verify_jwt = false
